export const environment = {
  production: true,
  supabaseUrl: 'https://ioxhyweqedmptfntzfja.supabase.co',
  supabaseKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveGh5d2VxZWRtcHRmbnR6ZmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjIwMTMxNDEsImV4cCI6MTk3NzU4OTE0MX0.qaMdQEG5YY-CmkkVeYJjhmKXnE89L6QcqbhWZl4WXzw.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlveGh5d2VxZWRtcHRmbnR6ZmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjIwMTMxNDEsImV4cCI6MTk3NzU4OTE0MX0.qaMdQEG5YY-CmkkVeYJjhmKXnE89L6QcqbhWZl4WXzw',
};
